# Author: Claudio <3261958605@qq.com>
# Created: 2017-07-04 17:33:08
# Commentary:
#+TITLE: 鲜活照片批量处理

#+BEGIN_QUOTE
Version: 0.2.1
#+END_QUOTE

* 功能

  将单个文件夹中的照片按相机自动生产的文件名排序。

  默认为一辆车有3张照片，重命名为20170712001-{1..3}.JPG形式。其中日期
  默认为当日日期。在设置中填写“昨天车辆数”后，会将对应照片新名称中的日
  期向后缩减一天。

* 运行方式

  解压压缩包，在文件夹（或子文件夹）中双击“app.exe”即可执行。

* 用法

  #+BEGIN_QUOTE
  此处应该有截图！！！
  #+END_QUOTE

  1. 点击“选择”按钮，选择需重命名照片所在文件夹。

  2. 点击“执行”按钮，执行重命名。

** 设置选项

   1. “昨天车辆数”：填写昨天车辆数,默认为0。只能为纯数字，如果值大于照
      片数量对应的车辆数，会自动报错。

   2. “是否在当前文件夹中修改”：默认会将重命名后的照片放在“原文件夹
      名.NEW”文件中。如果勾选此选项，会直接在照片原来所在文件夹中修改。
      （处于测试阶段，为防止照片丢失，不建议使用。）

   3. “昨天已编辑好车辆数”：表示昨天已近处理好的车辆数。默认为0，填写
      时只能为纯数字。比如填写“3”，见天为"2017-07-14"，且昨天车辆数不
      为0，则重命名时第一张照片应该为“20170713004-1.JPG”。

   #+BEGIN_QUOTE
   “昨天已编辑车辆数”默认为禁用状态，当输入“昨天未处理车辆数”后，按下
   “回车键”，如果填写内容合法，则会自动启用“昨天已编辑车辆数”输入框，
   并将光标移至该输入框内。

   同样，如果“昨天已编辑车辆数”填写完毕后，按下“回车键”，如果填写内容
   合法，光标会自动移至“是否在当前文件夹中修改”的选择框内。
   #+END_QUOTE

** 添加和删除照片

   需修改文件夹中的照片数量如果不合法，即不为3的整数倍，将自动报错。

*** 删除照片

    如果文件夹中照片名称符合相机默认生产的文件名，删除照片不会影响重命
    名结果。

*** 添加照片

    如需添加照片，新照片名称需先重命名，格式需为“1X2”、“10x2”形式，表示
    第几辆车的第几张照片。“x”号前的数字表示第几辆车，“x”后的数字表示该
    车的第几张图片。其中“x”大小写均可，数字前面个有“0”，如“01X002”为合
    法命名方式。

    执行重命名时，会根据文件夹中照片数量自动检查对添加照片的命名方式是
    否合法。即“x”前面的数字不能大于照片数量对应的车辆数，“x”后面的数字
    只能为1-3。

* TODO Todo

** 执行过程中“执行”按钮应该为灰色

** 可修改单个车的3张照片，实现“车头->车身->车尾”排序

   1. 选择操作车辆的索引
   2. 选择另外5种排序可能中的一种

** 当前文件夹中修改时，“resolution”是否使用随机字符串？
